export const getAllEngineersApi="/api/engineers/all";
export const createEngineerApi="/api/engineers/create";
export const deleteEngineerApi="/api/engineers/delete/"; //it takes the Engineer id
// export const activateEngineerApi="/api/users/activate";
export const getAllCunsultingEngineersApi="/api/consultingEngineers/all";
export const getAllConsultingCompaniesApi="/api/consultingCompany/all";
export const deleteConsultingCompanyApi="/api/consultingCompany/delete/";
export const createConsultingCompanyApi="/api/consultingCompany/create";
export const getAllOwnersApi="/api/owner/all";
export const deleteOwnerApi="/api/owner/delete/";
export const createOwnerApi="/api/owner/create";
export const createProjectApi="/api/project/create";
export const getAllProjectsApi="/api/project/all";